version: "3.9"

services:
  nginx:
    image: nginx:1.21.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - auth-shield
    volumes:
      - ./infra/confs/servers/:/etc/nginx/conf.d/
      - ./infra/confs/ssl/:/var/www/ssl
      - ../var/logs/nginx:/var/log/nginx
      - ../api:/var/www/html

  php:
    build:
      context: ../api
      dockerfile: ../infra/php.dockerfile
    container_name: php
    volumes:
      - ../api:/var/www/html
      - ../var/logs/php:/var/log/php-fpm
    ports:
      - "9000:9000"
    networks:
      - auth-shield

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    volumes:
      - ./infra/confs/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: auth_shield
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - auth-shield

networks:
  auth-shield:
    driver: bridge